trigger:
  - main

pool:
  vmImage: ubuntu-latest

steps:
  - task: UseDotNet@2
    inputs:
      version: '9.0.x'

  - script: dotnet restore
    displayName: Restore

  - script: dotnet build --no-restore
    displayName: Build

  - script: dotnet test --no-build
    displayName: Run Tests
    
  - task: Docker@2
    displayName: Build Docker Image
    inputs:
      command: build
      repository: knowledgevault-api
      Dockerfile: '**/Dockerfile'
      tags: |
        $(Build.BuildId)